#!/bin/bash

NAME="usendhome"                                    # Name of the application
DJANGODIR=/webapps/us_shipping_oscar              # Django project directory
SOCKFILE=/webapps/us_shipping_oscar/run/gunicorn.sock  # we will communicte using this unix socket
USER=usendhome                                        # the user to run as
GROUP=webapps                                     # the group to run as
NUM_WORKERS=5                                     # how many worker processes should Gunicorn spawn 2 * num_cores + 1
DJANGO_SETTINGS_MODULE=packageshop.settings             # which settings file should Django use
DJANGO_WSGI_MODULE=packageshop.wsgi                    # WSGI module name

echo "Starting $NAME as `whoami`"

# Activate the virtual environment
cd $DJANGODIR
source bin/activate
export DJANGO_SETTINGS_MODULE=$DJANGO_SETTINGS_MODULE
export PYTHONPATH=$DJANGODIR:$PYTHONPATH

# Create the run directory if it doesn't exist
RUNDIR=$(dirname $SOCKFILE)
test -d $RUNDIR || mkdir -p $RUNDIR

# Start your Django Unicorn
# Programs meant to be run under supervisor should not daemonize themselves (do not use --daemon)
exec bin/gunicorn ${DJANGO_WSGI_MODULE}:application \
  --name $NAME \
  --timeout 60 \
  --workers $NUM_WORKERS \
  --user=$USER --group=$GROUP \
  --log-level=info \
  --bind=unix:$SOCKFILE \
  --log-file=-
